(* begin-documentation-node
###########################
  IO Supplemental Packages
###########################


.. toctree::
   :maxdepth: 2
   :caption: Development:
   :hidden:

   ../Examples/Examples  [suplib/Examples.rst]
   ../BASIC/BASIC        [suplib/BASIC.rst]
   ../C/C                [suplib/C.rst]
   ../Go/Go              [suplib/Go.rst]
   ../Pascal/Pascal      [suplib/Pascal.rst]

Supplemental and contributed modules here...

https://github.com/io-core/Mod/blob/main/Suite.Mod

end-documentation-node *)


(* begin-package-description
### _Package Overview:_
The Suite package manages:
* contributions
### _Package Use:_

Explanation...

### _Modules in this package:_
end-package-description *)

(* begin-module-use-description
Module Suite handles:
* Nothing yet. Placeholder.

end-module-use-description *)
MODULE Suite; 
  IMPORT SYSTEM;

  CONST 

  TYPE 

  VAR 

  (* begin-section-description
## ---------- Generate Documentation
  end-section-description *)

  (* begin-procedure-description
---
**Foo** is a placeholder
  end-procedure-description *)
  PROCEDURE Foo;
  BEGIN 
  END Foo;



END Suite.
