(* begin-documentation-node
##################
  IO Style Guide
##################

Coding Guidelines
=================

On your own system, anything goes. Code intended for a PUll Request to Integrated Oberon however should aspire to simplicity, clarity, and generality.

Commit Message Conventions
==========================

Please be more clear and descriptive than charlesap

Pull Request Process
====================

fork, hack, pull, merge, post!

Bug Report Checklist
====================

File general issues in the
* [IO Project Issue Tracker](https://github.com/io-core/io/issues)

or in sub-project issue trackers for the following sub-projects:
* [doc](https://github.com/io-core/doc/issues)
* [Kernel](https://github.com/io-core/Kernel/issues)
* [Files](https://github.com/io-core/Files/issues)
* [Modules](https://github.com/io-core/Modules/issues)
* [Edit](https://github.com/io-core/Edit/issues)
* [Oberon](https://github.com/io-core/Oberon/issues)
* [System](https://github.com/io-core/System/issues)
* [Build](https://github.com/io-core/Build/issues)
* [Draw](https://github.com/io-core/Draw/issues)



https://github.com/io-core/Mod/blob/main/Vet.Mod

end-documentation-node *)


(* begin-module-use-description
Module Vet handles:
* Nothing yet. Placeholder.

end-module-use-description *)
MODULE Vet; 
  IMPORT SYSTEM;

  CONST 

  TYPE 

  VAR 

  (* begin-section-description
## ---------- Generate Documentation
  end-section-description *)

  (* begin-procedure-description
---
**Foo** is a placeholder
  end-procedure-description *)
  PROCEDURE Foo;
  BEGIN 
  END Foo;



END Vet.
